
_B='username.sf'
_A='r'
import os
path=os.getcwd()
bosver='clbos-3.0.1'
dfdr='~'
directory=dfdr
user=open(_B,_A)
password=open('password.sf',_A)
running=1
def cmnds():
	Bb='-line50.py';Ba='-line49.py';BZ='-line48.py';BY='-line47.py';BX='-line46.py';BW='-line45.py';BV='-line44.py';BU='-line43.py';BT='-line42.py';BS='-line41.py';BR='-line40.py';BQ='-line39.py';BP='-line38.py';BO='-line37.py';BN='-line36.py';BM='-line35.py';BL='-line34.py';BK='-line33.py';BJ='-line32.py';BI='-line31.py';BH='-line30.py';BG='-line29.py';BF='-line28.py';BE='-line27.py';BD='-line26.py';BC='-line25.py';BB='-line24.py';BA='-line23.py';B9='-line22.py';B8='-line21.py';B7='-line20.py';B6='-line19.py';B5='-line18.py';B4='-line17.py';B3='-line16.py';B2='-line15.py';B1='-line14.py';B0='-line13.py';A_='-line12.py';Az='-line11.py';Ay='-line10.py';Ax='-line9.py';Aw='-line8.py';Av='-line7.py';Au='-line6.py';At='-line5.py';As='-line4.py';Ar='-line3.py';Aq='-line2.py';Ap='-line1.py';Ao='-line50.clb';An='-line49.clb';Am='-line48.clb';Al='-line47.clb';Ak='-line46.clb';Aj='-line45.clb';Ai='-line44.clb';Ah='-line43.clb';Ag='-line42.clb';Af='-line41.clb';Ae='-line40.clb';Ad='-line39.clb';Ac='-line38.clb';Ab='-line37.clb';Aa='-line36.clb';AZ='-line35.clb';AY='-line34.clb';AX='-line33.clb';AW='-line32.clb';AV='-line31.clb';AU='-line30.clb';AT='-line29.clb';AS='-line28.clb';AR='-line27.clb';AQ='-line26.clb';AP='-line25.clb';AO='-line24.clb';AN='-line23.clb';AM='-line22.clb';AL='-line21.clb';AK='-line20.clb';AJ='-line19.clb';AI='-line18.clb';AH='-line17.clb';AG='-line16.clb';AF='-line15.clb';AE='-line14.clb';AD='-line13.clb';AC='-line12.clb';AB='-line11.clb';AA='-line10.clb';A9='-line9.clb';A8='-line8.clb';A7='-line7.clb';A6='-line6.clb';A5='-line5.clb';A4='-line4.clb';A3='-line3.clb';A2='-line2.clb';A1='-line1.clb';A0='sum $ ';Z='File Name $ ';Y='Script Name $ ';X='=====================================================================================';W='Directory $ ';V='ERROR: No Space Left.';U=' ';T=' $';S='sminpd';R='sminpmu';Q='sminpm';P='sminpp';O='minpd';N='minpmu';M='minpm';L='minpp';K='rvb';J='svb';I='ipi';H='inp';G='print';F='.var';E='x';D='w';C='Second $ ';B='/';A='First $ '
	if cmnd=='dfn':print(path)
	if cmnd=='help':print('clbasic / CLBasic / Code a Program in CLBasic');print('clbasrun / Run CLBasic / Run A CLBasic Script.');print('dfn / Directory Full Name / Get full name of the directory CLBOS is located in.');print('cdr / Change Directory / See the files of a different directory.');print('help / Help / Get all commands.');print('cun / Change Username / Replace existing Username with another one.');print('cpw / Change Password / Replace existing Password with another one.');print('cnf / Create New File / Create a file, with file type and name.');print('wdtf / Write data to File / Write text to a file you have created.');print('rdff / Read data from File / Read text from a file you have created.');print('del / Delete / Delete a specific file you have created.');print('echo / Echo / Echo a message to the system.');print('add / Add / Add 2 Numbers together.');print('sub / Subtract / Subtract 2 Numbers together.');print('mul / Multiply / Multiply 2 Numbers together.');print('div / Divide / Divide 2 Numbers together.');print('cls / Clear Screen / Clear Everything From The Screen/Terminal.')
	if cmnd=='cun':username=input('Overwrite Username $ ');u=open('username.txt',D);u.write(username);u.close()
	if cmnd=='cdr':dtct=input(W);print(os.listdir(dtct))
	if cmnd=='cpw':nwpw=input('New Password $ ');p=open('password.txt',D);p.write(nwpw);p.close()
	if cmnd=='clbasic':print(X);print("Welcome To CLBasic 1.1, For Elements; Read 'README' File.");print(X);Line1=input('1 | ');Line2=input('2 | ');Line3=input('3 | ');Line4=input('4 | ');Line5=input('5 | ');Line6=input('6 | ');Line7=input('7 | ');Line8=input('8 | ');Line9=input('9 | ');Line10=input('10| ');Line11=input('11| ');Line12=input('12| ');Line13=input('13| ');Line14=input('14| ');Line15=input('15| ');Line16=input('16| ');Line17=input('17| ');Line18=input('18| ');Line19=input('19| ');Line20=input('20| ');Line21=input('21| ');Line22=input('22| ');Line23=input('23| ');Line24=input('24| ');Line25=input('25| ');Line26=input('26| ');Line27=input('27| ');Line28=input('28| ');Line29=input('29| ');Line30=input('30| ');Line31=input('31| ');Line32=input('32| ');Line33=input('33| ');Line34=input('34| ');Line35=input('35| ');Line36=input('36| ');Line37=input('37| ');Line38=input('38| ');Line39=input('39| ');Line40=input('40| ');Line41=input('41| ');Line42=input('42| ');Line43=input('43| ');Line44=input('44| ');Line45=input('45| ');Line46=input('46| ');Line47=input('47| ');Line48=input('48| ');Line49=input('49| ');Line50=input('50| ');ScriptName=input(Y);SaveInDir=input(W);L1=open(SaveInDir+B+ScriptName+A1,E);L1W=open(SaveInDir+B+ScriptName+A1,D);L1W.write(Line1);L2=open(SaveInDir+B+ScriptName+A2,E);L2W=open(SaveInDir+B+ScriptName+A2,D);L2W.write(Line2);L3=open(SaveInDir+B+ScriptName+A3,E);L3W=open(SaveInDir+B+ScriptName+A3,D);L3W.write(Line3);L4=open(SaveInDir+B+ScriptName+A4,E);L4W=open(SaveInDir+B+ScriptName+A4,D);L4W.write(Line4);L5=open(SaveInDir+B+ScriptName+A5,E);L5W=open(SaveInDir+B+ScriptName+A5,D);L5W.write(Line5);L6=open(SaveInDir+B+ScriptName+A6,E);L6W=open(SaveInDir+B+ScriptName+A6,D);L6W.write(Line6);L7=open(SaveInDir+B+ScriptName+A7,E);L7W=open(SaveInDir+B+ScriptName+A7,D);L7W.write(Line7);L8=open(SaveInDir+B+ScriptName+A8,E);L8W=open(SaveInDir+B+ScriptName+A8,D);L8W.write(Line8);L9=open(SaveInDir+B+ScriptName+A9,E);L9W=open(SaveInDir+B+ScriptName+A9,D);L9W.write(Line9);L10=open(SaveInDir+B+ScriptName+AA,E);L10W=open(SaveInDir+B+ScriptName+AA,D);L10W.write(Line10);L11=open(SaveInDir+B+ScriptName+AB,E);L11W=open(SaveInDir+B+ScriptName+AB,D);L11W.write(Line11);L12=open(SaveInDir+B+ScriptName+AC,E);L12W=open(SaveInDir+B+ScriptName+AC,D);L12W.write(Line12);L13=open(SaveInDir+B+ScriptName+AD,E);L13W=open(SaveInDir+B+ScriptName+AD,D);L13W.write(Line13);L14=open(SaveInDir+B+ScriptName+AE,E);L14W=open(SaveInDir+B+ScriptName+AE,D);L14W.write(Line14);L15=open(SaveInDir+B+ScriptName+AF,E);L15W=open(SaveInDir+B+ScriptName+AF,D);L15W.write(Line15);L16=open(SaveInDir+B+ScriptName+AG,E);L16W=open(SaveInDir+B+ScriptName+AG,D);L16W.write(Line16);L17=open(SaveInDir+B+ScriptName+AH,E);L17W=open(SaveInDir+B+ScriptName+AH,D);L17W.write(Line17);L18=open(SaveInDir+B+ScriptName+AI,E);L18W=open(SaveInDir+B+ScriptName+AI,D);L18W.write(Line18);L19=open(SaveInDir+B+ScriptName+AJ,E);L19W=open(SaveInDir+B+ScriptName+AJ,D);L19W.write(Line19);L20=open(SaveInDir+B+ScriptName+AK,E);L20W=open(SaveInDir+B+ScriptName+AK,D);L20W.write(Line20);L21=open(SaveInDir+B+ScriptName+AL,E);L21W=open(SaveInDir+B+ScriptName+AL,D);L21W.write(Line21);L22=open(SaveInDir+B+ScriptName+AM,E);L22W=open(SaveInDir+B+ScriptName+AM,D);L22W.write(Line22);L23=open(SaveInDir+B+ScriptName+AN,E);L23W=open(SaveInDir+B+ScriptName+AN,D);L23W.write(Line23);L24=open(SaveInDir+B+ScriptName+AO,E);L24W=open(SaveInDir+B+ScriptName+AO,D);L24W.write(Line24);L25=open(SaveInDir+B+ScriptName+AP,E);L25W=open(SaveInDir+B+ScriptName+AP,D);L25W.write(Line25);L26=open(SaveInDir+B+ScriptName+AQ,E);L26W=open(SaveInDir+B+ScriptName+AQ,D);L26W.write(Line26);L27=open(SaveInDir+B+ScriptName+AR,E);L27W=open(SaveInDir+B+ScriptName+AR,D);L27W.write(Line27);L28=open(SaveInDir+B+ScriptName+AS,E);L28W=open(SaveInDir+B+ScriptName+AS,D);L28W.write(Line28);L29=open(SaveInDir+B+ScriptName+AT,E);L29W=open(SaveInDir+B+ScriptName+AT,D);L29W.write(Line29);L30=open(SaveInDir+B+ScriptName+AU,E);L30W=open(SaveInDir+B+ScriptName+AU,D);L30W.write(Line30);L31=open(SaveInDir+B+ScriptName+AV,E);L31W=open(SaveInDir+B+ScriptName+AV,D);L31W.write(Line31);L32=open(SaveInDir+B+ScriptName+AW,E);L32W=open(SaveInDir+B+ScriptName+AW,D);L32W.write(Line32);L33=open(SaveInDir+B+ScriptName+AX,E);L33W=open(SaveInDir+B+ScriptName+AX,D);L33W.write(Line33);L34=open(SaveInDir+B+ScriptName+AY,E);L34W=open(SaveInDir+B+ScriptName+AY,D);L34W.write(Line34);L35=open(SaveInDir+B+ScriptName+AZ,E);L35W=open(SaveInDir+B+ScriptName+AZ,D);L35W.write(Line35);L36=open(SaveInDir+B+ScriptName+Aa,E);L36W=open(SaveInDir+B+ScriptName+Aa,D);L36W.write(Line36);L37=open(SaveInDir+B+ScriptName+Ab,E);L37W=open(SaveInDir+B+ScriptName+Ab,D);L37W.write(Line37);L38=open(SaveInDir+B+ScriptName+Ac,E);L38W=open(SaveInDir+B+ScriptName+Ac,D);L38W.write(Line38);L39=open(SaveInDir+B+ScriptName+Ad,E);L39W=open(SaveInDir+B+ScriptName+Ad,D);L39W.write(Line39);L40=open(SaveInDir+B+ScriptName+Ae,E);L40W=open(SaveInDir+B+ScriptName+Ae,D);L40W.write(Line40);L41=open(SaveInDir+B+ScriptName+Af,E);L41W=open(SaveInDir+B+ScriptName+Af,D);L41W.write(Line41);L42=open(SaveInDir+B+ScriptName+Ag,E);L42W=open(SaveInDir+B+ScriptName+Ag,D);L42W.write(Line42);L43=open(SaveInDir+B+ScriptName+Ah,E);L43W=open(SaveInDir+B+ScriptName+Ah,D);L43W.write(Line43);L44=open(SaveInDir+B+ScriptName+Ai,E);L44W=open(SaveInDir+B+ScriptName+Ai,D);L44W.write(Line44);L45=open(SaveInDir+B+ScriptName+Aj,E);L45W=open(SaveInDir+B+ScriptName+Aj,D);L45W.write(Line45);L46=open(SaveInDir+B+ScriptName+Ak,E);L46W=open(SaveInDir+B+ScriptName+Ak,D);L46W.write(Line46);L47=open(SaveInDir+B+ScriptName+Al,E);L47W=open(SaveInDir+B+ScriptName+Al,D);L47W.write(Line47);L48=open(SaveInDir+B+ScriptName+Am,E);L48W=open(SaveInDir+B+ScriptName+Am,D);L48W.write(Line48);L49=open(SaveInDir+B+ScriptName+An,E);L49W=open(SaveInDir+B+ScriptName+An,D);L49W.write(Line49);L50=open(SaveInDir+B+ScriptName+Ao,E);L50W=open(SaveInDir+B+ScriptName+Ao,D);L50W.write(Line50);print("To Execute script, Use the command 'clbasrun'.")
	if cmnd=='clbasrun':
		ScriptName=input(Y);SaveInDir=input(W);L1R=open(SaveInDir+B+ScriptName+A1,_A);L1R=L1R.read();L2R=open(SaveInDir+B+ScriptName+A2,_A);L2R=L2R.read();L3R=open(SaveInDir+B+ScriptName+A3,_A);L3R=L3R.read();L4R=open(SaveInDir+B+ScriptName+A4,_A);L4R=L4R.read();L5R=open(SaveInDir+B+ScriptName+A5,_A);L5R=L5R.read();L6R=open(SaveInDir+B+ScriptName+A6,_A);L6R=L6R.read();L7R=open(SaveInDir+B+ScriptName+A7,_A);L7R=L7R.read();L8R=open(SaveInDir+B+ScriptName+A8,_A);L8R=L8R.read();L9R=open(SaveInDir+B+ScriptName+A9,_A);L9R=L9R.read();L10R=open(SaveInDir+B+ScriptName+AA,_A);L10R=L10R.read();L11R=open(SaveInDir+B+ScriptName+AB,_A);L11R=L11R.read();L12R=open(SaveInDir+B+ScriptName+AC,_A);L12R=L12R.read();L13R=open(SaveInDir+B+ScriptName+AD,_A);L13R=L13R.read();L14R=open(SaveInDir+B+ScriptName+AE,_A);L14R=L14R.read();L15R=open(SaveInDir+B+ScriptName+AF,_A);L15R=L15R.read();L16R=open(SaveInDir+B+ScriptName+AG,_A);L16R=L16R.read();L17R=open(SaveInDir+B+ScriptName+AH,_A);L17R=L17R.read();L18R=open(SaveInDir+B+ScriptName+AI,_A);L18R=L18R.read();L19R=open(SaveInDir+B+ScriptName+AJ,_A);L19R=L19R.read();L20R=open(SaveInDir+B+ScriptName+AK,_A);L20R=L20R.read();L21R=open(SaveInDir+B+ScriptName+AL,_A);L21R=L21R.read();L22R=open(SaveInDir+B+ScriptName+AM,_A);L22R=L22R.read();L23R=open(SaveInDir+B+ScriptName+AN,_A);L23R=L23R.read();L24R=open(SaveInDir+B+ScriptName+AO,_A);L24R=L24R.read();L25R=open(SaveInDir+B+ScriptName+AP,_A);L25R=L25R.read();L26R=open(SaveInDir+B+ScriptName+AQ,_A);L26R=L26R.read();L27R=open(SaveInDir+B+ScriptName+AR,_A);L27R=L27R.read();L28R=open(SaveInDir+B+ScriptName+AS,_A);L28R=L28R.read();L29R=open(SaveInDir+B+ScriptName+AT,_A);L29R=L29R.read();L30R=open(SaveInDir+B+ScriptName+AU,_A);L30R=L30R.read();L31R=open(SaveInDir+B+ScriptName+AV,_A);L31R=L31R.read();L32R=open(SaveInDir+B+ScriptName+AW,_A);L32R=L32R.read();L33R=open(SaveInDir+B+ScriptName+AX,_A);L33R=L33R.read();L34R=open(SaveInDir+B+ScriptName+AY,_A);L34R=L34R.read();L35R=open(SaveInDir+B+ScriptName+AZ,_A);L35R=L35R.read();L36R=open(SaveInDir+B+ScriptName+Aa,_A);L36R=L36R.read();L37R=open(SaveInDir+B+ScriptName+Ab,_A);L37R=L37R.read();L38R=open(SaveInDir+B+ScriptName+Ac,_A);L38R=L38R.read();L39R=open(SaveInDir+B+ScriptName+Ad,_A);L39R=L39R.read();L40R=open(SaveInDir+B+ScriptName+Ae,_A);L40R=L40R.read();L41R=open(SaveInDir+B+ScriptName+Af,_A);L41R=L41R.read();L42R=open(SaveInDir+B+ScriptName+Ag,_A);L42R=L42R.read();L43R=open(SaveInDir+B+ScriptName+Ah,_A);L43R=L43R.read();L44R=open(SaveInDir+B+ScriptName+Ai,_A);L44R=L44R.read();L45R=open(SaveInDir+B+ScriptName+Aj,_A);L45R=L45R.read();L46R=open(SaveInDir+B+ScriptName+Ak,_A);L46R=L46R.read();L47R=open(SaveInDir+B+ScriptName+Al,_A);L47R=L47R.read();L48R=open(SaveInDir+B+ScriptName+Am,_A);L48R=L48R.read();L49R=open(SaveInDir+B+ScriptName+An,_A);L49R=L49R.read();L50R=open(SaveInDir+B+ScriptName+Ao,_A);L50R=L50R.read()
		if L1R==G:print(L2R)
		if L1R==H:a=input(L2R+T+U)
		if L1R==I:print('ERROR: No Previous Input.')
		if L1R==J:vn=L2R;v=L3R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L1R==K:vs=L2R;vr=open(vs+F,_A);print(vr.read())
		if L1R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L1R==M:fv=input(A);sv=input('Second $');inpsm=float(fv)-float(sv);print(inpsm)
		if L1R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L1R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L1R==P:fv=input(A);inpsm=float(L2R)+float(fv);print(inpsm)
		if L1R==Q:fv=input(A);inpsm=float(L2R)-float(fv);print(inpsm)
		if L1R==R:fv=input(A);inpsm=float(L2R)*float(fv);print(inpsm)
		if L1R==S:fv=input(A);inpsm=float(L2R)/float(fv);print(inpsm)
		if L2R==G:print(L3R)
		if L2R==H:b=input(L3R+T+U);print(b)
		if L2R==I:
			prinp=a;equals_to_var=L3R;ipi_then=L4R;ipi_else=L5R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L2R==J:vn=L3R;v=L4R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L2R==K:vs=L3R;vr=open(vs+F,_A);print(vr.read())
		if L2R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L2R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L2R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L2R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L2R==P:fv=input(A);inpsm=float(L3R)+float(fv);print(inpsm)
		if L2R==Q:fv=input(A);inpsm=float(L3R)-float(fv);print(inpsm)
		if L2R==R:fv=input(A);inpsm=float(L3R)*float(fv);print(inpsm)
		if L2R==S:fv=input(A);inpsm=float(L3R)/float(fv);print(inpsm)
		if L3R==G:print(L4R)
		if L3R==H:c=input(L4R+T+U);print(c)
		if L3R==I:
			prinp=b;equals_to_var=L4R;ipi_then=L5R;ipi_else=L6R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L3R==J:vn=L4R;v=L5R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L3R==K:vs=L4R;vr=open(vs+F,_A);print(vr.read())
		if L3R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L3R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L3R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L3R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L3R==P:fv=input(A);inpsm=float(L4R)+float(fv);print(inpsm)
		if L3R==Q:fv=input(A);inpsm=float(L4R)-float(fv);print(inpsm)
		if L3R==R:fv=input(A);inpsm=float(L4R)*float(fv);print(inpsm)
		if L3R==S:fv=input(A);inpsm=float(L4R)/float(fv);print(inpsm)
		if L4R==G:print(L5R)
		if L4R==H:d=input(L5R+T+U);print(d)
		if L4R==I:
			prinp=c;equals_to_var=L5R;ipi_then=L6R;ipi_else=L7R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L4R==J:vn=L5R;v=L6R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L4R==K:vs=L5R;vr=open(vs+F,_A);print(vr.read())
		if L4R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L4R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L4R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L4R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L4R==P:fv=input(A);inpsm=float(L5R)+float(fv);print(inpsm)
		if L4R==Q:fv=input(A);inpsm=float(L5R)-float(fv);print(inpsm)
		if L4R==R:fv=input(A);inpsm=float(L5R)*float(fv);print(inpsm)
		if L4R==S:fv=input(A);inpsm=float(L5R)/float(fv);print(inpsm)
		if L5R==G:print(L6R)
		if L5R==H:e=input(L6R+T+U);print(e)
		if L5R==I:
			prinp=d;equals_to_var=L6R;ipi_then=L7R;ipi_else=L8R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L5R==J:vn=L6R;v=L7R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L5R==K:vs=L6R;vr=open(vs+F,_A);print(vr.read())
		if L5R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L5R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L5R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L5R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L5R==P:fv=input(A);inpsm=float(L6R)+float(fv);print(inpsm)
		if L5R==Q:fv=input(A);inpsm=float(L6R)-float(fv);print(inpsm)
		if L5R==R:fv=input(A);inpsm=float(L6R)*float(fv);print(inpsm)
		if L5R==S:fv=input(A);inpsm=float(L6R)/float(fv);print(inpsm)
		if L6R==G:print(L7R)
		if L6R==H:f=input(L7R+T+U);print(f)
		if L6R==I:
			prinp=e;equals_to_var=L7R;ipi_then=L8R;ipi_else=L9R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L6R==J:vn=L7R;v=L8R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L6R==K:vs=L7R;vr=open(vs+F,_A);print(vr.read())
		if L6R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L6R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L6R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L6R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L6R==P:fv=input(A);inpsm=float(L7R)+float(fv);print(inpsm)
		if L6R==Q:fv=input(A);inpsm=float(L7R)-float(fv);print(inpsm)
		if L6R==R:fv=input(A);inpsm=float(L7R)*float(fv);print(inpsm)
		if L6R==S:fv=input(A);inpsm=float(L7R)/float(fv);print(inpsm)
		if L7R==G:print(L8R)
		if L7R==H:g=input(L8R+T+'')
		if L7R==I:
			prinp=f;equals_to_var=L8R;ipi_then=L9R;ipi_else=L10R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L7R==J:vn=L8R;v=L9R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L7R==K:vs=L8R;vr=open(vs+F,_A);print(vr.read())
		if L7R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L7R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L7R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L7R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L7R==P:fv=input(A);inpsm=float(L8R)+float(fv);print(inpsm)
		if L7R==Q:fv=input(A);inpsm=float(L8R)-float(fv);print(inpsm)
		if L7R==R:fv=input(A);inpsm=float(L8R)*float(fv);print(inpsm)
		if L7R==S:fv=input(A);inpsm=float(L8R)/float(fv);print(inpsm)
		if L8R==G:print(L9R)
		if L8R==H:h=input(L9R+T+U);print(h)
		if L8R==I:
			prinp=g;equals_to_var=L9R;ipi_then=L10R;ipi_else=L11R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L8R==J:vn=L9R;v=L10R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L8R==K:vs=L9R;vr=open(vs+F,_A);print(vr.read())
		if L8R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L8R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L8R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L8R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L8R==P:fv=input(A);inpsm=float(L9R)+float(fv);print(inpsm)
		if L8R==Q:fv=input(A);inpsm=float(L9R)-float(fv);print(inpsm)
		if L8R==R:fv=input(A);inpsm=float(L9R)*float(fv);print(inpsm)
		if L8R==S:fv=input(A);inpsm=float(L9R)/float(fv);print(inpsm)
		if L9R==G:print(L10R)
		if L9R==H:i=input(L10R+T+U);print(i)
		if L9R==I:
			prinp=h;equals_to_var=L10R;ipi_then=L11R;ipi_else=L12R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L9R==J:vn=L10R;v=L11R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L9R==K:vs=L10R;vr=open(vs+F,_A);print(vr.read())
		if L9R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L9R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L9R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L9R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L9R==P:fv=input(A);inpsm=float(L10R)+float(fv);print(inpsm)
		if L9R==Q:fv=input(A);inpsm=float(L10R)-float(fv);print(inpsm)
		if L9R==R:fv=input(A);inpsm=float(L10R)*float(fv);print(inpsm)
		if L9R==S:fv=input(A);inpsm=float(L10R)/float(fv);print(inpsm)
		if L10R==G:print(L11R)
		if L10R==H:j=input(L11R+T+U);print(j)
		if L10R==J:vn=L11R;v=L12R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L10R==K:vs=L11R;vr=open(vs+F,_A);print(vr.read())
		if L10R==I:
			prinp=i;equals_to_var=L11R;ipi_then=L12R;ipi_else=L13R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L10R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L10R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L10R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L10R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L10R==P:fv=input(A);inpsm=float(L11R)+float(fv);print(inpsm)
		if L10R==Q:fv=input(A);inpsm=float(L11R)-float(fv);print(inpsm)
		if L10R==R:fv=input(A);inpsm=float(L11R)*float(fv);print(inpsm)
		if L10R==S:fv=input(A);inpsm=float(L11R)/float(fv);print(inpsm)
		if L11R==G:print(L12R)
		if L11R==H:k=input(L12R+T+U);print(k)
		if L11R==J:vn=L12R;v=L13R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L11R==K:vs=L12R;vr=open(vs+F,_A);print(vr.read())
		if L11R==I:
			prinp=j;equals_to_var=L12R;ipi_then=L13R;ipi_else=L14R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L11R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L11R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L11R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L11R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L11R==P:fv=input(A);inpsm=float(L12R)+float(fv);print(inpsm)
		if L11R==Q:fv=input(A);inpsm=float(L12R)-float(fv);print(inpsm)
		if L11R==R:fv=input(A);inpsm=float(L12R)*float(fv);print(inpsm)
		if L11R==S:fv=input(A);inpsm=float(L12R)/float(fv);print(inpsm)
		if L12R==G:print(L13R)
		if L12R==H:l=input(L13R+T+U);print(l)
		if L12R==J:vn=L13R;v=L14R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L12R==K:vs=L13R;vr=open(vs+F,_A);print(vr.read())
		if L12R==I:
			prinp=k;equals_to_var=L13R;ipi_then=L14R;ipi_else=L15R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L12R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L12R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L12R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L12R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L12R==P:fv=input(A);inpsm=float(L13R)+float(fv);print(inpsm)
		if L12R==Q:fv=input(A);inpsm=float(L13R)-float(fv);print(inpsm)
		if L12R==R:fv=input(A);inpsm=float(L13R)*float(fv);print(inpsm)
		if L12R==S:fv=input(A);inpsm=float(L13R)/float(fv);print(inpsm)
		if L13R==G:print(L14R)
		if L13R==H:m=input(L14R+T+U);print(m)
		if L13R==J:vn=L14R;v=L15R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L13R==K:vs=L14R;vr=open(vs+F,_A);print(vr.read())
		if L13R==I:
			prinp=l;equals_to_var=L14R;ipi_then=L15R;ipi_else=L16R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L13R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L13R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L13R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L13R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L13R==P:fv=input(A);inpsm=float(L13R)+float(fv);print(inpsm)
		if L13R==Q:fv=input(A);inpsm=float(L13R)-float(fv);print(inpsm)
		if L13R==R:fv=input(A);inpsm=float(L13R)*float(fv);print(inpsm)
		if L13R==S:fv=input(A);inpsm=float(L13R)/float(fv);print(inpsm)
		if L14R==G:print(L15R)
		if L14R==H:n=input(L15R+T+U);print(n)
		if L14R==J:vn=L15R;v=L16R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L14R==K:vs=L15R;vr=open(vs+F,_A);print(vr.read())
		if L14R==I:
			prinp=m;equals_to_var=L15R;ipi_then=L16R;ipi_else=L17R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L14R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L14R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L14R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L14R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L14R==P:fv=input(A);inpsm=float(L15R)+float(fv);print(inpsm)
		if L14R==Q:fv=input(A);inpsm=float(L15R)-float(fv);print(inpsm)
		if L14R==R:fv=input(A);inpsm=float(L15R)*float(fv);print(inpsm)
		if L14R==S:fv=input(A);inpsm=float(L15R)/float(fv);print(inpsm)
		if L15R==G:print(L16R)
		if L15R==H:o=input(L16R+T+U);print(o)
		if L15R==J:vn=L16R;v=L17R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L15R==K:vs=L16R;vr=open(vs+F,_A);print(vr.read())
		if L15R==I:
			prinp=n;equals_to_var=L16R;ipi_then=L17R;ipi_else=L18R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L15R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L15R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L15R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L15R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L15R==P:fv=input(A);inpsm=float(L16R)+float(fv);print(inpsm)
		if L15R==Q:fv=input(A);inpsm=float(L16R)-float(fv);print(inpsm)
		if L15R==R:fv=input(A);inpsm=float(L16R)*float(fv);print(inpsm)
		if L15R==S:fv=input(A);inpsm=float(L16R)/float(fv);print(inpsm)
		if L16R==G:print(L17R)
		if L16R==H:p=input(L17R+T+U);print(p)
		if L16R==J:vn=L17R;v=L18R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L16R==K:vs=L17R;vr=open(vs+F,_A);print(vr.read())
		if L16R==I:
			prinp=o;equals_to_var=L17R;ipi_then=L18R;ipi_else=L19R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L16R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L16R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L16R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L16R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L16R==P:fv=input(A);inpsm=float(L17R)+float(fv);print(inpsm)
		if L16R==Q:fv=input(A);inpsm=float(L17R)-float(fv);print(inpsm)
		if L16R==R:fv=input(A);inpsm=float(L17R)*float(fv);print(inpsm)
		if L16R==S:fv=input(A);inpsm=float(L17R)/float(fv);print(inpsm)
		if L17R==G:print(L18R)
		if L17R==H:q=input(L18R+T+U);print(q)
		if L17R==J:vn=L18R;v=L19R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L17R==K:vs=L18R;vr=open(vs+F,_A);print(vr.read())
		if L17R==I:
			prinp=p;equals_to_var=L18R;ipi_then=L19R;ipi_else=L20R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L17R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L17R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L17R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L17R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L17R==P:fv=input(A);inpsm=float(L18R)+float(fv);print(inpsm)
		if L17R==Q:fv=input(A);inpsm=float(L18R)-float(fv);print(inpsm)
		if L17R==R:fv=input(A);inpsm=float(L18R)*float(fv);print(inpsm)
		if L17R==S:fv=input(A);inpsm=float(L18R)/float(fv);print(inpsm)
		if L18R==G:print(L19R)
		if L18R==H:r=input(L19R+T+U);print(r)
		if L18R==J:vn=L19R;v=L20R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L18R==K:vs=L19R;vr=open(vs+F,_A);print(vr.read())
		if L18R==I:
			prinp=q;equals_to_var=L19R;ipi_then=L20R;ipi_else=L21R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L18R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L18R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L18R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L18R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L18R==P:fv=input(A);inpsm=float(L19R)+float(fv);print(inpsm)
		if L18R==Q:fv=input(A);inpsm=float(L19R)-float(fv);print(inpsm)
		if L18R==R:fv=input(A);inpsm=float(L19R)*float(fv);print(inpsm)
		if L18R==S:fv=input(A);inpsm=float(L19R)/float(fv);print(inpsm)
		if L19R==G:print(L20R)
		if L19R==H:s=input(L20R+T+U);print(s)
		if L19R==J:vn=L20R;v=L21R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L19R==K:vs=L20R;vr=open(vs+F,_A);print(vr.read())
		if L19R==I:
			prinp=r;equals_to_var=L20R;ipi_then=L21R;ipi_else=L22R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L19R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L19R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L19R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L19R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L19R==P:fv=input(A);inpsm=float(L20R)+float(fv);print(inpsm)
		if L19R==Q:fv=input(A);inpsm=float(L20R)-float(fv);print(inpsm)
		if L19R==R:fv=input(A);inpsm=float(L20R)*float(fv);print(inpsm)
		if L19R==S:fv=input(A);inpsm=float(L20R)/float(fv);print(inpsm)
		if L20R==G:print(L21R)
		if L20R==H:t=input(L21R+T+U);print(t)
		if L20R==J:vn=L21R;v=L22R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L20R==K:vs=L21R;vr=open(vs+F,_A);print(vr.read())
		if L20R==I:
			prinp=s;equals_to_var=L21R;ipi_then=L22R;ipi_else=L23R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L20R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L20R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L20R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L20R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L20R==P:fv=input(A);inpsm=float(L21R)+float(fv);print(inpsm)
		if L20R==Q:fv=input(A);inpsm=float(L21R)-float(fv);print(inpsm)
		if L20R==R:fv=input(A);inpsm=float(L21R)*float(fv);print(inpsm)
		if L20R==S:fv=input(A);inpsm=float(L21R)/float(fv);print(inpsm)
		if L21R==G:print(L22R)
		if L21R==H:u=input(L22R+T+U);print(u)
		if L21R==J:vn=L22R;v=L23R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(v)
		if L21R==K:vs=L22R;vr=open(vs+F,_A);print(vr.read())
		if L21R==I:
			prinp=t;equals_to_var=L22R;ipi_then=L23R;ipi_else=L24R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L21R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L21R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L21R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L21R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L21R==P:fv=input(A);inpsm=float(L22R)+float(fv);print(inpsm)
		if L21R==Q:fv=input(A);inpsm=float(L22R)-float(fv);print(inpsm)
		if L21R==R:fv=input(A);inpsm=float(L22R)*float(fv);print(inpsm)
		if L21R==S:fv=input(A);inpsm=float(L22R)/float(fv);print(inpsm)
		if L22R==G:print(L23R)
		if L22R==H:v=input(L23R+T+U);print(v)
		if L22R==J:vn=L23R;vbw=L24R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L22R==K:vs=L23R;vr=open(vs+F,_A);print(vr.read())
		if L22R==I:
			prinp=u;equals_to_var=L23R;ipi_then=L24R;ipi_else=L25R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L22R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L22R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L22R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L22R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L22R==P:fv=input(A);inpsm=float(L23R)+float(fv);print(inpsm)
		if L22R==Q:fv=input(A);inpsm=float(L23R)-float(fv);print(inpsm)
		if L22R==R:fv=input(A);inpsm=float(L23R)*float(fv);print(inpsm)
		if L22R==S:fv=input(A);inpsm=float(L23R)/float(fv);print(inpsm)
		if L23R==G:print(L24R)
		if L23R==H:w=input(L24R+T+U);print(w)
		if L23R==J:vn=L24R;vbw=L25R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L23R==K:vs=L24R;vr=open(vs+F,_A);print(vr.read())
		if L23R==I:
			prinp=v;equals_to_var=L24R;ipi_then=L25R;ipi_else=L26R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L23R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L23R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L23R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L23R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L23R==P:fv=input(A);inpsm=float(L24R)+float(fv);print(inpsm)
		if L23R==Q:fv=input(A);inpsm=float(L24R)-float(fv);print(inpsm)
		if L23R==R:fv=input(A);inpsm=float(L24R)*float(fv);print(inpsm)
		if L23R==S:fv=input(A);inpsm=float(L24R)/float(fv);print(inpsm)
		if L24R==G:print(L25R)
		if L24R==H:x=input(L25R+T+U);print(x)
		if L24R==J:vn=L25R;vbw=L26R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L24R==K:vs=L25R;vr=open(vs+F,_A);print(vr.read())
		if L24R==I:
			prinp=w;equals_to_var=L25R;ipi_then=L26R;ipi_else=L27R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L24R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L24R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L24R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L24R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L24R==P:fv=input(A);inpsm=float(L25R)+float(fv);print(inpsm)
		if L24R==Q:fv=input(A);inpsm=float(L25R)-float(fv);print(inpsm)
		if L24R==R:fv=input(A);inpsm=float(L25R)*float(fv);print(inpsm)
		if L24R==S:fv=input(A);inpsm=float(L25R)/float(fv);print(inpsm)
		if L25R==G:print(L26R)
		if L25R==H:y=input(L26R+T+U);print(y)
		if L25R==J:vn=L26R;vbw=L27R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L25R==K:vs=L26R;vr=open(vs+F,_A);print(vr.read())
		if L25R==I:
			prinp=x;equals_to_var=L26R;ipi_then=L27R;ipi_else=L28R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L25R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L25R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L25R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L25R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L25R==P:fv=input(A);inpsm=float(L26R)+float(fv);print(inpsm)
		if L25R==Q:fv=input(A);inpsm=float(L26R)-float(fv);print(inpsm)
		if L25R==R:fv=input(A);inpsm=float(L26R)*float(fv);print(inpsm)
		if L25R==S:fv=input(A);inpsm=float(L26R)/float(fv);print(inpsm)
		if L26R==G:print(L27R)
		if L26R==H:z=input(L27R+T+U);print(z)
		if L26R==J:vn=L27R;vbw=L28R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L26R==K:vs=L27R;vr=open(vs+F,_A);print(vr.read())
		if L26R==I:
			prinp=y;equals_to_var=L27R;ipi_then=L28R;ipi_else=L29R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L26R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L26R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L26R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L26R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L26R==P:fv=input(A);inpsm=float(L27R)+float(fv);print(inpsm)
		if L26R==Q:fv=input(A);inpsm=float(L27R)-float(fv);print(inpsm)
		if L26R==R:fv=input(A);inpsm=float(L27R)*float(fv);print(inpsm)
		if L26R==S:fv=input(A);inpsm=float(L27R)/float(fv);print(inpsm)
		if L27R==G:print(L28R)
		if L27R==H:aa=input(L28R+T+U);print(aa)
		if L27R==J:vn=L28R;vbw=L29R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L27R==K:vs=L28R;vr=open(vs+F,_A);print(vr.read())
		if L27R==I:
			prinp=z;equals_to_var=L28R;ipi_then=L29R;ipi_else=L30R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L27R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L27R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L27R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L27R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L27R==P:fv=input(A);inpsm=float(L28R)+float(fv);print(inpsm)
		if L27R==Q:fv=input(A);inpsm=float(L28R)-float(fv);print(inpsm)
		if L27R==R:fv=input(A);inpsm=float(L28R)*float(fv);print(inpsm)
		if L27R==S:fv=input(A);inpsm=float(L28R)/float(fv);print(inpsm)
		if L28R==G:print(L29R)
		if L28R==H:ab=input(L29R+T+U);print(ab)
		if L28R==J:vn=L29R;vbw=L30R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L28R==K:vs=L29R;vr=open(vs+F,_A);print(vr.read())
		if L28R==I:
			prinp=aa;equals_to_var=L29R;ipi_then=L30R;ipi_else=L31R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L28R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L28R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L28R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L28R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L28R==P:fv=input(A);inpsm=float(L29R)+float(fv);print(inpsm)
		if L28R==Q:fv=input(A);inpsm=float(L29R)-float(fv);print(inpsm)
		if L28R==R:fv=input(A);inpsm=float(L29R)*float(fv);print(inpsm)
		if L28R==S:fv=input(A);inpsm=float(L29R)/float(fv);print(inpsm)
		if L29R==G:print(L30R)
		if L29R==H:ab=input(L30R+T+U);print(ab)
		if L29R==J:vn=L30R;vbw=L31R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L29R==K:vs=L30R;vr=open(vs+F,_A);print(vr.read())
		if L29R==I:
			prinp=aa;equals_to_var=L30R;ipi_then=L31R;ipi_else=L32R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L29R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L29R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L29R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L29R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L29R==P:fv=input(A);inpsm=float(L30R)+float(fv);print(inpsm)
		if L29R==Q:fv=input(A);inpsm=float(L30R)-float(fv);print(inpsm)
		if L29R==R:fv=input(A);inpsm=float(L30R)*float(fv);print(inpsm)
		if L29R==S:fv=input(A);inpsm=float(L30R)/float(fv);print(inpsm)
		if L30R==G:print(L31R)
		if L30R==H:ac=input(L31R+T+U);print(ac)
		if L30R==J:vn=L31R;vbw=L32R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L30R==K:vs=L31R;vr=open(vs+F,_A);print(vr.read())
		if L30R==I:
			prinp=ab;equals_to_var=L31R;ipi_then=L32R;ipi_else=L33R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L30R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L30R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L30R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L30R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L30R==P:fv=input(A);inpsm=float(L31R)+float(fv);print(inpsm)
		if L30R==Q:fv=input(A);inpsm=float(L31R)-float(fv);print(inpsm)
		if L30R==R:fv=input(A);inpsm=float(L31R)*float(fv);print(inpsm)
		if L30R==S:fv=input(A);inpsm=float(L31R)/float(fv);print(inpsm)
		if L31R==G:print(L32R)
		if L31R==H:ac=input(L32R+T+U);print(ac)
		if L31R==J:vn=L32R;vbw=L33R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L31R==K:vs=L32R;vr=open(vs+F,_A);print(vr.read())
		if L31R==I:
			prinp=ab;equals_to_var=L32R;ipi_then=L33R;ipi_else=L34R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L31R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L31R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L31R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L31R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L31R==P:fv=input(A);inpsm=float(L32R)+float(fv);print(inpsm)
		if L31R==Q:fv=input(A);inpsm=float(L32R)-float(fv);print(inpsm)
		if L31R==R:fv=input(A);inpsm=float(L32R)*float(fv);print(inpsm)
		if L31R==S:fv=input(A);inpsm=float(L32R)/float(fv);print(inpsm)
		if L32R==G:print(L33R)
		if L32R==H:ad=input(L33R+T+U);print(ad)
		if L32R==J:vn=L33R;vbw=L34R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L32R==K:vs=L33R;vr=open(vs+F,_A);print(vr.read())
		if L32R==I:
			prinp=ac;equals_to_var=L33R;ipi_then=L34R;ipi_else=L35R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L32R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L32R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L32R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L32R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L32R==P:fv=input(A);inpsm=float(L33R)+float(fv);print(inpsm)
		if L32R==Q:fv=input(A);inpsm=float(L33R)-float(fv);print(inpsm)
		if L32R==R:fv=input(A);inpsm=float(L33R)*float(fv);print(inpsm)
		if L32R==S:fv=input(A);inpsm=float(L33R)/float(fv);print(inpsm)
		if L33R==G:print(L34R)
		if L33R==H:ae=input(L34R+T+U);print(ae)
		if L33R==J:vn=L34R;vbw=L35R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L33R==K:vs=L34R;vr=open(vs+F,_A);print(vr.read())
		if L33R==I:
			prinp=ad;equals_to_var=L34R;ipi_then=L35R;ipi_else=L36R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L33R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L33R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L33R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L33R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L33R==P:fv=input(A);inpsm=float(L34R)+float(fv);print(inpsm)
		if L33R==Q:fv=input(A);inpsm=float(L34R)-float(fv);print(inpsm)
		if L33R==R:fv=input(A);inpsm=float(L34R)*float(fv);print(inpsm)
		if L33R==S:fv=input(A);inpsm=float(L34R)/float(fv);print(inpsm)
		if L34R==G:print(L35R)
		if L34R==H:af=input(L35R+T+U);print(af)
		if L34R==J:vn=L35R;vbw=L36R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L34R==K:vs=L35R;vr=open(vs+F,_A);print(vr.read())
		if L34R==I:
			prinp=ae;equals_to_var=L35R;ipi_then=L36R;ipi_else=L37R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L34R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L34R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L34R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L34R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L34R==P:fv=input(A);inpsm=float(L35R)+float(fv);print(inpsm)
		if L34R==Q:fv=input(A);inpsm=float(L35R)-float(fv);print(inpsm)
		if L34R==R:fv=input(A);inpsm=float(L35R)*float(fv);print(inpsm)
		if L34R==S:fv=input(A);inpsm=float(L35R)/float(fv);print(inpsm)
		if L35R==G:print(L36R)
		if L35R==H:ag=input(L36R+T+U);print(ag)
		if L35R==J:vn=L36R;vbw=L37R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L35R==K:vs=L36R;vr=open(vs+F,_A);print(vr.read())
		if L35R==I:
			prinp=af;equals_to_var=L36R;ipi_then=L37R;ipi_else=L38R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L35R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L35R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L35R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L35R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L35R==P:fv=input(A);inpsm=float(L36R)+float(fv);print(inpsm)
		if L35R==Q:fv=input(A);inpsm=float(L36R)-float(fv);print(inpsm)
		if L35R==R:fv=input(A);inpsm=float(L36R)*float(fv);print(inpsm)
		if L35R==S:fv=input(A);inpsm=float(L36R)/float(fv);print(inpsm)
		if L36R==G:print(L37R)
		if L36R==H:ah=input(L37R+T+U);print(ah)
		if L36R==J:vn=L37R;vbw=L38R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L36R==K:vs=L37R;vr=open(vs+F,_A);print(vr.read())
		if L36R==I:
			prinp=ag;equals_to_var=L37R;ipi_then=L38R;ipi_else=L39R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L36R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L36R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L36R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L36R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L36R==P:fv=input(A);inpsm=float(L37R)+float(fv);print(inpsm)
		if L36R==Q:fv=input(A);inpsm=float(L37R)-float(fv);print(inpsm)
		if L36R==R:fv=input(A);inpsm=float(L37R)*float(fv);print(inpsm)
		if L36R==S:fv=input(A);inpsm=float(L37R)/float(fv);print(inpsm)
		if L37R==G:print(L38R)
		if L37R==H:ai=input(L38R+T+U);print(ai)
		if L37R==J:vn=L38R;vbw=L39R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L37R==K:vs=L38R;vr=open(vs+F,_A);print(vr.read())
		if L37R==I:
			prinp=ah;equals_to_var=L38R;ipi_then=L39R;ipi_else=L40R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L37R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L37R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L37R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L37R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L37R==P:fv=input(A);inpsm=float(L38R)+float(fv);print(inpsm)
		if L37R==Q:fv=input(A);inpsm=float(L38R)-float(fv);print(inpsm)
		if L37R==R:fv=input(A);inpsm=float(L38R)*float(fv);print(inpsm)
		if L37R==S:fv=input(A);inpsm=float(L38R)/float(fv);print(inpsm)
		if L38R==G:print(L39R)
		if L38R==H:aj=input(L39R+T+U);print(aj)
		if L38R==J:vn=L39R;vbw=L40R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L38R==K:vs=L39R;vr=open(vs+F,_A);print(vr.read())
		if L38R==I:
			prinp=ai;equals_to_var=L39R;ipi_then=L40R;ipi_else=L41R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L38R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L38R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L38R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L38R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L38R==P:fv=input(A);inpsm=float(L39R)+float(fv);print(inpsm)
		if L38R==Q:fv=input(A);inpsm=float(L39R)-float(fv);print(inpsm)
		if L38R==R:fv=input(A);inpsm=float(L39R)*float(fv);print(inpsm)
		if L38R==S:fv=input(A);inpsm=float(L39R)/float(fv);print(inpsm)
		if L39R==G:print(L40R)
		if L39R==H:ak=input(L40R+T+U);print(ak)
		if L39R==J:vn=L40R;vbw=L41R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L39R==K:vs=L40R;vr=open(vs+F,_A);print(vr.read())
		if L39R==I:
			prinp=aj;equals_to_var=L40R;ipi_then=L41R;ipi_else=L42R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L39R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L39R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L39R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L39R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L39R==P:fv=input(A);inpsm=float(L40R)+float(fv);print(inpsm)
		if L39R==Q:fv=input(A);inpsm=float(L40R)-float(fv);print(inpsm)
		if L39R==R:fv=input(A);inpsm=float(L40R)*float(fv);print(inpsm)
		if L39R==S:fv=input(A);inpsm=float(L40R)/float(fv);print(inpsm)
		if L40R==G:print(L41R)
		if L40R==H:al=input(L41R+T+U);print(al)
		if L40R==J:vn=L41R;vbw=L42R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L40R==K:vs=L41R;vr=open(vs+F,_A);print(vr.read())
		if L40R==I:
			prinp=ak;equals_to_var=L41R;ipi_then=L42R;ipi_else=L43R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L40R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L40R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L40R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L40R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L40R==P:fv=input(A);inpsm=float(L41R)+float(fv);print(inpsm)
		if L40R==Q:fv=input(A);inpsm=float(L41R)-float(fv);print(inpsm)
		if L40R==R:fv=input(A);inpsm=float(L41R)*float(fv);print(inpsm)
		if L40R==S:fv=input(A);inpsm=float(L41R)/float(fv);print(inpsm)
		if L41R==G:print(L42R)
		if L41R==H:am=input(L42R+T+U);print(am)
		if L41R==J:vn=L42R;vbw=L43R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L41R==K:vs=L42R;vr=open(vs+F,_A);print(vr.read())
		if L41R==I:
			prinp=al;equals_to_var=L42R;ipi_then=L43R;ipi_else=L44R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L41R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L41R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L41R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L41R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L41R==P:fv=input(A);inpsm=float(L42R)+float(fv);print(inpsm)
		if L41R==Q:fv=input(A);inpsm=float(L42R)-float(fv);print(inpsm)
		if L41R==R:fv=input(A);inpsm=float(L42R)*float(fv);print(inpsm)
		if L41R==S:fv=input(A);inpsm=float(L42R)/float(fv);print(inpsm)
		if L42R==G:print(L43R)
		if L42R==H:an=input(L43R+T+U);print(an)
		if L42R==J:vn=L43R;vbw=L44R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L42R==K:vs=L43R;vr=open(vs+F,_A);print(vr.read())
		if L42R==I:
			prinp=am;equals_to_var=L43R;ipi_then=L44R;ipi_else=L45R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L42R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L42R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L42R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L42R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L42R==P:fv=input(A);inpsm=float(L43R)+float(fv);print(inpsm)
		if L42R==Q:fv=input(A);inpsm=float(L43R)-float(fv);print(inpsm)
		if L42R==R:fv=input(A);inpsm=float(L43R)*float(fv);print(inpsm)
		if L42R==S:fv=input(A);inpsm=float(L43R)/float(fv);print(inpsm)
		if L43R==G:print(L44R)
		if L43R==H:an=input(L44R+T+U);print(an)
		if L43R==J:vn=L44R;vbw=L45R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L43R==K:vs=L44R;vr=open(vs+F,_A);print(vr.read())
		if L43R==I:
			prinp=am;equals_to_var=L44R;ipi_then=L45R;ipi_else=L46R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L43R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L43R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L43R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L43R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L43R==P:fv=input(A);inpsm=float(L44R)+float(fv);print(inpsm)
		if L43R==Q:fv=input(A);inpsm=float(L44R)-float(fv);print(inpsm)
		if L43R==R:fv=input(A);inpsm=float(L44R)*float(fv);print(inpsm)
		if L43R==S:fv=input(A);inpsm=float(L44R)/float(fv);print(inpsm)
		if L44R==G:print(L45R)
		if L44R==H:ao=input(L45R+T+U);print(ao)
		if L44R==J:vn=L45R;vbw=L46R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L44R==K:vs=L45R;vr=open(vs+F,_A);print(vr.read())
		if L44R==I:
			prinp=an;equals_to_var=L45R;ipi_then=L46R;ipi_else=L47R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L44R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L44R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L44R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L44R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L44R==P:fv=input(A);inpsm=float(L45R)+float(fv);print(inpsm)
		if L44R==Q:fv=input(A);inpsm=float(L45R)-float(fv);print(inpsm)
		if L44R==R:fv=input(A);inpsm=float(L45R)*float(fv);print(inpsm)
		if L44R==S:fv=input(A);inpsm=float(L45R)/float(fv);print(inpsm)
		if L45R==G:print(L46R)
		if L45R==H:ap=input(L46R+T+U);print(ap)
		if L45R==J:vn=L46R;vbw=L47R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L45R==K:vs=L46R;vr=open(vs+F,_A);print(vr.read())
		if L45R==I:
			prinp=ao;equals_to_var=L46R;ipi_then=L47R;ipi_else=L48R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L45R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L45R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L45R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L45R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L45R==P:fv=input(A);inpsm=float(L46R)+float(fv);print(inpsm)
		if L45R==Q:fv=input(A);inpsm=float(L46R)-float(fv);print(inpsm)
		if L45R==R:fv=input(A);inpsm=float(L46R)*float(fv);print(inpsm)
		if L45R==S:fv=input(A);inpsm=float(L46R)/float(fv);print(inpsm)
		if L46R==G:print(L47R)
		if L46R==H:aq=input(L47R+T+U);print(aq)
		if L46R==J:vn=L47R;vbw=L48R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L46R==K:vs=L47R;vr=open(vs+F,_A);print(vr.read())
		if L46R==I:
			prinp=ap;equals_to_var=L47R;ipi_then=L48R;ipi_else=L49R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L46R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L46R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L46R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L46R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L46R==P:fv=input(A);inpsm=float(L47R)+float(fv);print(inpsm)
		if L46R==Q:fv=input(A);inpsm=float(L47R)-float(fv);print(inpsm)
		if L46R==R:fv=input(A);inpsm=float(L47R)*float(fv);print(inpsm)
		if L46R==S:fv=input(A);inpsm=float(L47R)/float(fv);print(inpsm)
		if L47R==G:print(L48R)
		if L47R==H:ar=input(L48R+T+U);print(ar)
		if L47R==J:vn=L48R;vbw=L49R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L47R==K:vs=L48R;vr=open(vs+F,_A);print(vr.read())
		if L47R==I:
			prinp=aq;equals_to_var=L48R;ipi_then=L49R;ipi_else=L50R
			if prinp==equals_to_var:print(ipi_then)
			if prinp!=equals_to_var:print(ipi_else)
		if L47R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L47R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L47R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L47R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L47R==P:fv=input(A);inpsm=float(L48R)+float(fv);print(inpsm)
		if L47R==Q:fv=input(A);inpsm=float(L48R)-float(fv);print(inpsm)
		if L47R==R:fv=input(A);inpsm=float(L48R)*float(fv);print(inpsm)
		if L47R==S:fv=input(A);inpsm=float(L48R)/float(fv);print(inpsm)
		if L48R==G:print(L49R)
		if L48R==H:asa=input(L49R+T+U);print(asa)
		if L48R==J:vn=L49R;vbw=L50R;svb=open(vn+F,E);svb=open(vn+F,D);svb.write(vbw)
		if L48R==K:vs=L49R;vr=open(vs+F,_A);print(vr.read())
		if L48R==I:print(V)
		if L48R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L48R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L48R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L48R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L48R==P:fv=input(A);inpsm=float(L49R)+float(fv);print(inpsm)
		if L48R==Q:fv=input(A);inpsm=float(L49R)-float(fv);print(inpsm)
		if L48R==R:fv=input(A);inpsm=float(L49R)*float(fv);print(inpsm)
		if L48R==S:fv=input(A);inpsm=float(L49R)/float(fv);print(inpsm)
		if L49R==G:print(L50R)
		if L49R==H:at=input(L50R+T+U);print(at)
		if L49R==J:print(V)
		if L49R==K:vs=L50R;vr=open(vs+F,_A);print(vr.read())
		if L49R==I:print(V)
		if L49R==L:fv=input(A);sv=input(C);inpsm=float(fv)+float(sv);print(inpsm)
		if L49R==M:fv=input(A);sv=input(C);inpsm=float(fv)-float(sv);print(inpsm)
		if L49R==N:fv=input(A);sv=input(C);inpsm=float(fv)*float(sv);print(inpsm)
		if L49R==O:fv=input(A);sv=input(C);inpsm=float(fv)/float(sv);print(inpsm)
		if L49R==P:fv=input(A);inpsm=float(L50R)+float(fv);print(inpsm)
		if L49R==Q:fv=input(A);inpsm=float(L50R)-float(fv);print(inpsm)
		if L49R==R:fv=input(A);inpsm=float(L50R)*float(fv);print(inpsm)
		if L49R==S:fv=input(A);inpsm=float(L50R)/float(fv);print(inpsm)
		if L50R==G:print(V)
		if L50R==H:print(V)
		if L50R==J:print(V)
		if L50R==K:print(V)
		if L50R==I:print(V)
		if L50R==L:print(V)
		if L50R==M:print(V)
		if L50R==N:print(V)
		if L50R==O:print(V)
		if L50R==P:print(V)
		if L50R==Q:print(V)
		if L50R==R:print(V)
		if L50R==S:print(V)
	if cmnd=='py':print(X);print('Welcome To Python Compiler 3.12.');print(X);Line1=input('1 | ');Line2=input('2 | ');Line3=input('3 | ');Line4=input('4 | ');Line5=input('5 | ');Line6=input('6 | ');Line7=input('7 | ');Line8=input('8 | ');Line9=input('9 | ');Line10=input('10| ');Line11=input('11| ');Line12=input('12| ');Line13=input('13| ');Line14=input('14| ');Line15=input('15| ');Line16=input('16| ');Line17=input('17| ');Line18=input('18| ');Line19=input('19| ');Line20=input('20| ');Line21=input('21| ');Line22=input('22| ');Line23=input('23| ');Line24=input('24| ');Line25=input('25| ');Line26=input('26| ');Line27=input('27| ');Line28=input('28| ');Line29=input('29| ');Line30=input('30| ');Line31=input('31| ');Line32=input('32| ');Line33=input('33| ');Line34=input('34| ');Line35=input('35| ');Line36=input('36| ');Line37=input('37| ');Line38=input('38| ');Line39=input('39| ');Line40=input('40| ');Line41=input('41| ');Line42=input('42| ');Line43=input('43| ');Line44=input('44| ');Line45=input('45| ');Line46=input('46| ');Line47=input('47| ');Line48=input('48| ');Line49=input('49| ');Line50=input('50| ');ScriptName=input(Y);SaveInDir=input(W);L1=open(SaveInDir+B+ScriptName+Ap,E);L1W=open(SaveInDir+B+ScriptName+Ap,D);L1W.write(Line1);L2=open(SaveInDir+B+ScriptName+Aq,E);L2W=open(SaveInDir+B+ScriptName+Aq,D);L2W.write(Line2);L3=open(SaveInDir+B+ScriptName+Ar,E);L3W=open(SaveInDir+B+ScriptName+Ar,D);L3W.write(Line3);L4=open(SaveInDir+B+ScriptName+As,E);L4W=open(SaveInDir+B+ScriptName+As,D);L4W.write(Line4);L5=open(SaveInDir+B+ScriptName+At,E);L5W=open(SaveInDir+B+ScriptName+At,D);L5W.write(Line5);L6=open(SaveInDir+B+ScriptName+Au,E);L6W=open(SaveInDir+B+ScriptName+Au,D);L6W.write(Line6);L7=open(SaveInDir+B+ScriptName+Av,E);L7W=open(SaveInDir+B+ScriptName+Av,D);L7W.write(Line7);L8=open(SaveInDir+B+ScriptName+Aw,E);L8W=open(SaveInDir+B+ScriptName+Aw,D);L8W.write(Line8);L9=open(SaveInDir+B+ScriptName+Ax,E);L9W=open(SaveInDir+B+ScriptName+Ax,D);L9W.write(Line9);L10=open(SaveInDir+B+ScriptName+Ay,E);L10W=open(SaveInDir+B+ScriptName+Ay,D);L10W.write(Line10);L11=open(SaveInDir+B+ScriptName+Az,E);L11W=open(SaveInDir+B+ScriptName+Az,D);L11W.write(Line11);L12=open(SaveInDir+B+ScriptName+A_,E);L12W=open(SaveInDir+B+ScriptName+A_,D);L12W.write(Line12);L13=open(SaveInDir+B+ScriptName+B0,E);L13W=open(SaveInDir+B+ScriptName+B0,D);L13W.write(Line13);L14=open(SaveInDir+B+ScriptName+B1,E);L14W=open(SaveInDir+B+ScriptName+B1,D);L14W.write(Line14);L15=open(SaveInDir+B+ScriptName+B2,E);L15W=open(SaveInDir+B+ScriptName+B2,D);L15W.write(Line15);L16=open(SaveInDir+B+ScriptName+B3,E);L16W=open(SaveInDir+B+ScriptName+B3,D);L16W.write(Line16);L17=open(SaveInDir+B+ScriptName+B4,E);L17W=open(SaveInDir+B+ScriptName+B4,D);L17W.write(Line17);L18=open(SaveInDir+B+ScriptName+B5,E);L18W=open(SaveInDir+B+ScriptName+B5,D);L18W.write(Line18);L19=open(SaveInDir+B+ScriptName+B6,E);L19W=open(SaveInDir+B+ScriptName+B6,D);L19W.write(Line19);L20=open(SaveInDir+B+ScriptName+B7,E);L20W=open(SaveInDir+B+ScriptName+B7,D);L20W.write(Line20);L21=open(SaveInDir+B+ScriptName+B8,E);L21W=open(SaveInDir+B+ScriptName+B8,D);L21W.write(Line21);L22=open(SaveInDir+B+ScriptName+B9,E);L22W=open(SaveInDir+B+ScriptName+B9,D);L22W.write(Line22);L23=open(SaveInDir+B+ScriptName+BA,E);L23W=open(SaveInDir+B+ScriptName+BA,D);L23W.write(Line23);L24=open(SaveInDir+B+ScriptName+BB,E);L24W=open(SaveInDir+B+ScriptName+BB,D);L24W.write(Line24);L25=open(SaveInDir+B+ScriptName+BC,E);L25W=open(SaveInDir+B+ScriptName+BC,D);L25W.write(Line25);L26=open(SaveInDir+B+ScriptName+BD,E);L26W=open(SaveInDir+B+ScriptName+BD,D);L26W.write(Line26);L27=open(SaveInDir+B+ScriptName+BE,E);L27W=open(SaveInDir+B+ScriptName+BE,D);L27W.write(Line27);L28=open(SaveInDir+B+ScriptName+BF,E);L28W=open(SaveInDir+B+ScriptName+BF,D);L28W.write(Line28);L29=open(SaveInDir+B+ScriptName+BG,E);L29W=open(SaveInDir+B+ScriptName+BG,D);L29W.write(Line29);L30=open(SaveInDir+B+ScriptName+BH,E);L30W=open(SaveInDir+B+ScriptName+BH,D);L30W.write(Line30);L31=open(SaveInDir+B+ScriptName+BI,E);L31W=open(SaveInDir+B+ScriptName+BI,D);L31W.write(Line31);L32=open(SaveInDir+B+ScriptName+BJ,E);L32W=open(SaveInDir+B+ScriptName+BJ,D);L32W.write(Line32);L33=open(SaveInDir+B+ScriptName+BK,E);L33W=open(SaveInDir+B+ScriptName+BK,D);L33W.write(Line33);L34=open(SaveInDir+B+ScriptName+BL,E);L34W=open(SaveInDir+B+ScriptName+BL,D);L34W.write(Line34);L35=open(SaveInDir+B+ScriptName+BM,E);L35W=open(SaveInDir+B+ScriptName+BM,D);L35W.write(Line35);L36=open(SaveInDir+B+ScriptName+BN,E);L36W=open(SaveInDir+B+ScriptName+BN,D);L36W.write(Line36);L37=open(SaveInDir+B+ScriptName+BO,E);L37W=open(SaveInDir+B+ScriptName+BO,D);L37W.write(Line37);L38=open(SaveInDir+B+ScriptName+BP,E);L38W=open(SaveInDir+B+ScriptName+BP,D);L38W.write(Line38);L39=open(SaveInDir+B+ScriptName+BQ,E);L39W=open(SaveInDir+B+ScriptName+BQ,D);L39W.write(Line39);L40=open(SaveInDir+B+ScriptName+BR,E);L40W=open(SaveInDir+B+ScriptName+BR,D);L40W.write(Line40);L41=open(SaveInDir+B+ScriptName+BS,E);L41W=open(SaveInDir+B+ScriptName+BS,D);L41W.write(Line41);L42=open(SaveInDir+B+ScriptName+BT,E);L42W=open(SaveInDir+B+ScriptName+BT,D);L42W.write(Line42);L43=open(SaveInDir+B+ScriptName+BU,E);L43W=open(SaveInDir+B+ScriptName+BU,D);L43W.write(Line43);L44=open(SaveInDir+B+ScriptName+BV,E);L44W=open(SaveInDir+B+ScriptName+BV,D);L44W.write(Line44);L45=open(SaveInDir+B+ScriptName+BW,E);L45W=open(SaveInDir+B+ScriptName+BW,D);L45W.write(Line45);L46=open(SaveInDir+B+ScriptName+BX,E);L46W=open(SaveInDir+B+ScriptName+BX,D);L46W.write(Line46);L47=open(SaveInDir+B+ScriptName+BY,E);L47W=open(SaveInDir+B+ScriptName+BY,D);L47W.write(Line47);L48=open(SaveInDir+B+ScriptName+BZ,E);L48W=open(SaveInDir+B+ScriptName+BZ,D);L48W.write(Line48);L49=open(SaveInDir+B+ScriptName+Ba,E);L49W=open(SaveInDir+B+ScriptName+Ba,D);L49W.write(Line49);L50=open(SaveInDir+B+ScriptName+Bb,E);L50W=open(SaveInDir+B+ScriptName+Bb,D);L50W.write(Line50)
	if cmnd=='pyrun':ScriptName=input(Y);SaveInDir=input(W);L1R=open(SaveInDir+B+ScriptName+Ap,_A);L1R=L1R.read();L2R=open(SaveInDir+B+ScriptName+Aq,_A);L2R=L2R.read();L3R=open(SaveInDir+B+ScriptName+Ar,_A);L3R=L3R.read();L4R=open(SaveInDir+B+ScriptName+As,_A);L4R=L4R.read();L5R=open(SaveInDir+B+ScriptName+At,_A);L5R=L5R.read();L6R=open(SaveInDir+B+ScriptName+Au,_A);L6R=L6R.read();L7R=open(SaveInDir+B+ScriptName+Av,_A);L7R=L7R.read();L8R=open(SaveInDir+B+ScriptName+Aw,_A);L8R=L8R.read();L9R=open(SaveInDir+B+ScriptName+Ax,_A);L9R=L9R.read();L10R=open(SaveInDir+B+ScriptName+Ay,_A);L10R=L10R.read();L11R=open(SaveInDir+B+ScriptName+Az,_A);L11R=L11R.read();L12R=open(SaveInDir+B+ScriptName+A_,_A);L12R=L12R.read();L13R=open(SaveInDir+B+ScriptName+B0,_A);L13R=L13R.read();L14R=open(SaveInDir+B+ScriptName+B1,_A);L14R=L14R.read();L15R=open(SaveInDir+B+ScriptName+B2,_A);L15R=L15R.read();L16R=open(SaveInDir+B+ScriptName+B3,_A);L16R=L16R.read();L17R=open(SaveInDir+B+ScriptName+B4,_A);L17R=L17R.read();L18R=open(SaveInDir+B+ScriptName+B5,_A);L18R=L18R.read();L19R=open(SaveInDir+B+ScriptName+B6,_A);L19R=L19R.read();L20R=open(SaveInDir+B+ScriptName+B7,_A);L20R=L20R.read();L21R=open(SaveInDir+B+ScriptName+B8,_A);L21R=L21R.read();L22R=open(SaveInDir+B+ScriptName+B9,_A);L22R=L22R.read();L23R=open(SaveInDir+B+ScriptName+BA,_A);L23R=L23R.read();L24R=open(SaveInDir+B+ScriptName+BB,_A);L24R=L24R.read();L25R=open(SaveInDir+B+ScriptName+BC,_A);L25R=L25R.read();L26R=open(SaveInDir+B+ScriptName+BD,_A);L26R=L26R.read();L27R=open(SaveInDir+B+ScriptName+BE,_A);L27R=L27R.read();L28R=open(SaveInDir+B+ScriptName+BF,_A);L28R=L28R.read();L29R=open(SaveInDir+B+ScriptName+BG,_A);L29R=L29R.read();L30R=open(SaveInDir+B+ScriptName+BH,_A);L30R=L30R.read();L31R=open(SaveInDir+B+ScriptName+BI,_A);L31R=L31R.read();L32R=open(SaveInDir+B+ScriptName+BJ,_A);L32R=L32R.read();L33R=open(SaveInDir+B+ScriptName+BK,_A);L33R=L33R.read();L34R=open(SaveInDir+B+ScriptName+BL,_A);L34R=L34R.read();L35R=open(SaveInDir+B+ScriptName+BM,_A);L35R=L35R.read();L36R=open(SaveInDir+B+ScriptName+BN,_A);L36R=L36R.read();L37R=open(SaveInDir+B+ScriptName+BO,_A);L37R=L37R.read();L38R=open(SaveInDir+B+ScriptName+BP,_A);L38R=L38R.read();L39R=open(SaveInDir+B+ScriptName+BQ,_A);L39R=L39R.read();L40R=open(SaveInDir+B+ScriptName+BR,_A);L40R=L40R.read();L41R=open(SaveInDir+B+ScriptName+BS,_A);L41R=L41R.read();L42R=open(SaveInDir+B+ScriptName+BT,_A);L42R=L42R.read();L43R=open(SaveInDir+B+ScriptName+BU,_A);L43R=L43R.read();L44R=open(SaveInDir+B+ScriptName+BV,_A);L44R=L44R.read();L45R=open(SaveInDir+B+ScriptName+BW,_A);L45R=L45R.read();L46R=open(SaveInDir+B+ScriptName+BX,_A);L46R=L46R.read();L47R=open(SaveInDir+B+ScriptName+BY,_A);L47R=L47R.read();L48R=open(SaveInDir+B+ScriptName+BZ,_A);L48R=L48R.read();L49R=open(SaveInDir+B+ScriptName+Ba,_A);L49R=L49R.read();L50R=open(SaveInDir+B+ScriptName+Bb,_A);L50R=L50R.read();exec(f"""{L1R}
{L2R}
{L3R}
{L4R}
{L5R}
{L6R}
{L7R}
{L8R}
{L9R}
{L10R}
{L11R}
{L12R}
{L13R}
{L14R}
{L15R}
{L16R}
{L17R}
{L18R}
{L19R}
{L20R}
{L21R}
{L22R}
{L23R}
{L24R}
{L25R}
{L26R}
{L27R}
{L28R}
{L29R}
{L30R}
{L31R}
{L32R}
{L33R}
{L34R}
{L35R}
{L36R}
{L37R}
{L38R}
{L39R}
{L40R}
{L41R}
{L42R}
{L43R}
{L44R}
{L45R}
{L46R}
{L47R}
{L48R}
{L49R}
{L50R}""")
	if cmnd=='cnf':cnf=input(Z);cnf=open(cnf,E)
	if cmnd=='wdtf':cf=input(Z);wdtf=input('Text/Data $ ');p=open(cf,D);p.write(wdtf);p.close()
	if cmnd=='rdff':file_selected=input(Z);file_readed=open(file_selected,_A);print(file_readed.read())
	if cmnd=='echo':eh=input('Echo $ ');print(eh)
	if cmnd=='add':First=float(input(A));Second=float(input(C));sum=Second+First;print(A0+str(sum))
	if cmnd=='sub':First=float(input(A));Second=float(input(C));sum=Second-First;print(A0+str(sum))
	if cmnd=='mul':First=float(input(A));Second=float(input(C));sum=Second*First;print(A0+str(sum))
	if cmnd=='div':First=float(input(A));Second=float(input(C));sum=Second/First;print(A0+str(sum))
	if cmnd=='del':
		dlf=input(Z)
		if dlf!='CLBOS.py':os.remove(dlf)
	if cmnd=='cls':os.system('cls')
PIN=input('Password $ ')
if PIN==password.read():
	while running==1:user=open(_B,_A);print(user.read(),'@',bosver,'/ dir $',directory);cmnd=input('$ ');cmnds()
